In [516]:
!pip uninstall scikit-learn -y

Found existing installation: scikit-learn 1.0.2
Uninstalling scikit-learn-1.0.2:
  Successfully uninstalled scikit-learn-1.0.2


In [518]:
!pip uninstall scipy -y

In [521]:
!pip install --upgrade scipy==1.5.4

     ---------------------------------------- 31.4/31.4 MB 3.0 MB/s eta 0:00:00


In [522]:
!pip install --upgrade pip
!pip install --upgrade scikit-learn==0.23.0

  Using cached scikit_learn-0.23.0-cp39-cp39-win_amd64.whl


In [1]:
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import tensorflow
from keras.datasets import mnist
(X_train, y_train), (_, _) = mnist.load_data()

In [3]:
len(X_train)

60000

In [4]:
X_train.shape

(60000, 28, 28)

In [5]:
dim = 784 # 28*28
X_train = X_train.reshape(len(X_train), dim)

In [6]:
from sklearn.decomposition import PCA

pca = PCA(n_components=dim, svd_solver='full')
modelPCA = pca.fit(X_train)

X_dim_transformed = modelPCA.transform(X_train)

In [7]:
explained_variance = np.round(np.cumsum(pca.explained_variance_ratio_), 3)
explained_variance

array([0.097, 0.168, 0.23 , 0.284, 0.332, 0.375, 0.408, 0.437, 0.465,
       0.488, 0.509, 0.529, 0.547, 0.564, 0.579, 0.594, 0.607, 0.62 ,
       0.632, 0.644, 0.654, 0.664, 0.674, 0.683, 0.692, 0.7  , 0.708,
       0.716, 0.724, 0.731, 0.737, 0.744, 0.75 , 0.755, 0.761, 0.767,
       0.772, 0.777, 0.781, 0.786, 0.791, 0.795, 0.799, 0.803, 0.807,
       0.811, 0.815, 0.818, 0.821, 0.825, 0.828, 0.831, 0.834, 0.837,
       0.84 , 0.842, 0.845, 0.848, 0.85 , 0.853, 0.855, 0.857, 0.86 ,
       0.862, 0.864, 0.866, 0.868, 0.87 , 0.872, 0.874, 0.876, 0.878,
       0.879, 0.881, 0.883, 0.884, 0.886, 0.888, 0.889, 0.891, 0.892,
       0.893, 0.895, 0.896, 0.897, 0.899, 0.9  , 0.901, 0.903, 0.904,
       0.905, 0.906, 0.907, 0.908, 0.909, 0.911, 0.912, 0.913, 0.914,
       0.915, 0.916, 0.917, 0.918, 0.918, 0.919, 0.92 , 0.921, 0.922,
       0.923, 0.924, 0.924, 0.925, 0.926, 0.927, 0.928, 0.928, 0.929,
       0.93 , 0.93 , 0.931, 0.932, 0.933, 0.933, 0.934, 0.935, 0.935,
       0.936, 0.936,

In [8]:
len(list(filter(lambda x: x < 0.82,explained_variance)))

48

Answer for the first question is 49 components.

In [9]:
M = 49

In [10]:
pca = PCA(n_components=49, svd_solver='full')
modelPCA = pca.fit(X_train)

X_train = modelPCA.transform(X_train)

In [11]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_train, y_train, test_size=0.3, random_state=68)

In [12]:
len(X_train)

42000

In [13]:
np.sum(X_train[:,0])/len(X_train)

1.7137093856298877

In [14]:
from sklearn.multiclass import OneVsRestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

In [15]:
X_train.shape

(42000, 49)

In [16]:
y_train.shape

(42000,)

In [17]:
tree = RandomForestClassifier(criterion='gini', min_samples_leaf=10, max_depth=20, n_estimators=10, random_state=68)
clf_tree = OneVsRestClassifier(tree).fit(X_train, y_train)

In [18]:
X_train.shape

(42000, 49)

In [19]:
X_test.shape

(18000, 49)

In [20]:
y_train.shape

(42000,)

In [21]:
y_pred = clf_tree.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix
CM = confusion_matrix(y_test, y_pred)

In [23]:
CM

array([[1683,    0,    8,    7,    4,   15,   30,    2,    3,    2],
       [   2, 2016,   14,    3,    0,    6,    4,    8,    5,    2],
       [  20,    2, 1623,   13,   11,    6,   14,   29,   54,    6],
       [   8,    8,   45, 1591,    4,   42,   10,    8,   39,   22],
       [   6,   12,    7,    1, 1597,   10,   27,    5,   12,   61],
       [  20,    2,   10,   60,   15, 1405,   28,   11,   25,   17],
       [  17,    4,    8,    3,    4,   28, 1696,    0,    8,    2],
       [   6,   19,   25,    2,   22,    3,    1, 1746,    6,   48],
       [  16,   19,   29,   50,   12,   57,   12,   17, 1571,   28],
       [  11,   11,    6,   23,   83,   14,    1,   54,   16, 1622]],
      dtype=int64)

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
logreg = LogisticRegression(solver='lbfgs', random_state=68)

In [26]:
y_train.dtype

dtype('uint8')

In [27]:
X_train.dtype

dtype('float64')

In [28]:
clf_logreg = OneVsRestClassifier(logreg).fit(X_train, y_train)

c:\users\pogre\pycharmprojects\pythonproject1\final\venv\lib\site-packages\sklearn\linear_model\_logistic.py:760: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [29]:
y_pred = clf_logreg.predict(X_test)

In [30]:
CM = confusion_matrix(y_test, y_pred)
CM

array([[1689,    0,    8,    3,    0,   16,   18,    3,   14,    3],
       [   1, 2005,   10,    5,    0,   10,    3,    4,   19,    3],
       [  12,   15, 1543,   30,   36,   12,   26,   35,   55,   14],
       [   5,   10,   58, 1536,    3,   69,    9,   13,   45,   29],
       [   7,   12,   13,    3, 1573,    1,   23,    6,   13,   87],
       [  23,    8,   21,   77,   30, 1307,   40,    9,   48,   30],
       [   6,    5,   11,    3,   18,   22, 1693,    3,    7,    2],
       [   4,   14,   26,   11,   19,    8,    2, 1748,    6,   40],
       [  17,   62,   32,   53,   10,   70,   18,   10, 1495,   44],
       [   9,   16,   11,   35,   64,   21,    0,   74,   23, 1588]],
      dtype=int64)

In [31]:
des_tree = DecisionTreeClassifier(criterion='gini', min_samples_leaf=10, max_depth=20, random_state=68)
clf_des_tree = OneVsRestClassifier(des_tree).fit(X_train, y_train)

In [32]:
y_pred = clf_des_tree.predict(X_test)

In [33]:
CM = confusion_matrix(y_test, y_pred)
CM

array([[1589,    0,   26,   29,    4,   35,   33,    3,   23,   12],
       [   3, 1992,   14,    6,    2,   14,   11,    9,    8,    1],
       [  39,   11, 1481,   37,   25,   40,   25,   29,   63,   28],
       [  12,   11,   80, 1453,   11,   77,   18,   19,   68,   28],
       [  18,   15,   37,    6, 1426,   29,   35,   28,   22,  122],
       [  30,    3,   66,   79,   37, 1198,   50,   26,   57,   47],
       [  27,    3,   31,   13,   10,   41, 1602,    7,   22,   14],
       [  12,   12,   41,    7,   23,   15,    1, 1660,   16,   91],
       [  34,   16,  111,   79,   24,   88,   24,   23, 1381,   31],
       [  21,   11,   45,   38,  129,   29,    6,   74,   40, 1448]],
      dtype=int64)

In [34]:
import pandas as pd

In [35]:
data = pd.read_csv("pred_for_task.csv")

In [36]:
data

FileName  Label  f0  f1  f2  f3  f4  f5  f6  f7  ...  f774  f775  f776  \
0     file1      7   0   0   0   0   0   0   0   0  ...     0     0     0   
1     file2      2   0   0   0   0   0   0   0   0  ...     0     0     0   
2     file3      1   0   0   0   0   0   0   0   0  ...     0     0     0   
3     file4      0   0   0   0   0   0   0   0   0  ...     0     0     0   
4     file5      4   0   0   0   0   0   0   0   0  ...     0     0     0   
5     file6      1   0   0   0   0   0   0   0   0  ...     0     0     0   
6     file7      4   0   0   0   0   0   0   0   0  ...     0     0     0   
7     file8      9   0   0   0   0   0   0   0   0  ...     0     0     0   
8     file9      5   0   0   0   0   0   0   0   0  ...     0     0     0   
9    file10      9   0   0   0   0   0   0   0   0  ...     0     0     0   
10   file11      0   0   0   0   0   0   0   0   0  ...     0     0     0   
11   file12      6   0   0   0   0   0   0   0   0  ...     0     0     0   
12   file13      9   0   0   0   0   0   0   0   0  ...     0     0     0   
13   file14      0   0   0   0   0   0   0   0   0  ...     0     0     0   
14   file15      1   0   0   0   0   0   0   0   0  ...     0     0     0   
15   file16      5   0   0   0   0   0   0   0   0  ...     0     0     0   
16   file17      9   0   0   0   0   0   0   0   0  ...     0     0     0   
17   file18      7   0   0   0   0   0   0   0   0  ...     0     0     0   
18   file19      3   0   0   0   0   0   0   0   0  ...     0     0     0   
19   file20      4   0   0   0   0   0   0   0   0  ...     0     0     0   
20   file21      9   0   0   0   0   0   0   0   0  ...     0     0     0   
21   file22      6   0   0   0   0   0   0   0   0  ...     0     0     0   
22   file23      6   0   0   0   0   0   0   0   0  ...     0     0     0   
23   file24      5   0   0   0   0   0   0   0   0  ...     0     0     0   
24   file25      4   0   0   0   0   0   0   0   0  ...     0     0     0   
25   file26      0   0   0   0   0   0   0   0   0  ...     0     0     0   
26   file27      7   0   0   0   0   0   0   0   0  ...     0     0     0   
27   file28      4   0   0   0   0   0   0   0   0  ...     0     0     0   
28   file29      0   0   0   0   0   0   0   0   0  ...     0     0     0   
29   file30      1   0   0   0   0   0   0   0   0  ...     0     0     0   

    f777  f778  f779  f780  f781  f782  f783  
0      0     0     0     0     0     0     0  
1      0     0     0     0     0     0     0  
2      0     0     0     0     0     0     0  
3      0     0     0     0     0     0     0  
4      0     0     0     0     0     0     0  
5      0     0     0     0     0     0     0  
6      0     0     0     0     0     0     0  
7      0     0     0     0     0     0     0  
8      0     0     0     0     0     0     0  
9      0     0     0     0     0     0     0  
10     0     0     0     0     0     0     0  
11     0     0     0     0     0     0     0  
12     0     0     0     0     0     0     0  
13     0     0     0     0     0     0     0  
14     0     0     0     0     0     0     0  
15     0     0     0     0     0     0     0  
16     0     0     0     0     0     0     0  
17     0     0     0     0     0     0     0  
18     0     0     0     0     0     0     0  
19     0     0     0     0     0     0     0  
20     0     0     0     0     0     0     0  
21     0     0     0     0     0     0     0  
22     0     0     0     0     0     0     0  
23     0     0     0     0     0     0     0  
24     0     0     0     0     0     0     0  
25     0     0     0     0     0     0     0  
26     0     0     0     0     0     0     0  
27     0     0     0     0     0     0     0  
28     0     0     0     0     0     0     0  
29     0     0     0     0     0     0     0  

[30 rows x 786 columns]

In [37]:
data = data.drop(columns=["FileName","Label"])
data.head()

f0  f1  f2  f3  f4  f5  f6  f7  f8  f9  ...  f774  f775  f776  f777  f778  \
0   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   
1   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   
2   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   
3   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   
4   0   0   0   0   0   0   0   0   0   0  ...     0     0     0     0     0   

   f779  f780  f781  f782  f783  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     0     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 784 columns]

In [38]:
data = data.to_numpy()

In [39]:
data = modelPCA.transform(data)
data

array([[-332.27116927,  747.7987162 ,  -42.84481899, ...,   94.2118074 ,
         -59.04736467,   -7.63229899],
       [  20.69696209, -955.58458273, -152.71551708, ..., -262.65423458,
         105.63611463,  119.84537391],
       [-946.02686793, -430.84318261,   66.17633643, ...,  115.036273  ,
         -20.63915867,  132.37537739],
       ...,
       [ 224.98822327,  881.03842296, -180.92093117, ...,   49.99183667,
          66.86725258,  187.12632779],
       [1128.03797971, -354.99535818, -183.85326766, ...,  240.38677901,
         -25.81138928,   63.37802564],
       [-765.24057399, -154.13449942, -107.92304472, ...,  139.25934043,
          26.44104855,    4.60440769]])

In [40]:
data[17] # file18

array([ -16.76194237,  673.7894916 , -350.09123685, -263.33303208,
       -450.41764842,  -51.94632821,  453.58234139,  686.7585585 ,
       -300.13769065,   96.60450714,  173.45508167, -186.02953756,
        181.76629137, -106.75327533, -457.01903357, -268.70706529,
        167.23744251,  483.48379341,  157.97062525,  100.40954915,
        -89.01594647,   58.78565857,  254.93017315, -155.37032356,
         34.83151355,  161.16839764,  199.58332617,  181.09845589,
        -16.90741857, -166.189934  ,  -47.47116295, -364.30181655,
         38.50582035, -295.25751976, -101.08809189,  125.78288838,
       -192.60782117,    4.77115785,  -32.072715  ,   15.98946281,
       -170.06513505,  -47.26067531,  -36.62737424,   42.60510596,
        -37.21467808, -149.47239598,   77.58524539,   12.42406366,
         -5.04159084])

In [41]:
data[17].reshape(1,49)

array([[ -16.76194237,  673.7894916 , -350.09123685, -263.33303208,
        -450.41764842,  -51.94632821,  453.58234139,  686.7585585 ,
        -300.13769065,   96.60450714,  173.45508167, -186.02953756,
         181.76629137, -106.75327533, -457.01903357, -268.70706529,
         167.23744251,  483.48379341,  157.97062525,  100.40954915,
         -89.01594647,   58.78565857,  254.93017315, -155.37032356,
          34.83151355,  161.16839764,  199.58332617,  181.09845589,
         -16.90741857, -166.189934  ,  -47.47116295, -364.30181655,
          38.50582035, -295.25751976, -101.08809189,  125.78288838,
        -192.60782117,    4.77115785,  -32.072715  ,   15.98946281,
        -170.06513505,  -47.26067531,  -36.62737424,   42.60510596,
         -37.21467808, -149.47239598,   77.58524539,   12.42406366,
          -5.04159084]])

In [42]:
clf_tree.predict_proba(data[17].reshape(1,49))

array([[0.00000000e+00, 0.00000000e+00, 7.81405636e-02, 2.64038294e-02,
        0.00000000e+00, 1.75580025e-04, 0.00000000e+00, 8.80127646e-01,
        6.77021266e-03, 8.38216806e-03]])

In [43]:
data[14].reshape(1,49)

array([[-8.78175983e+02, -4.00637066e+02,  4.82033596e+01,
        -5.71506394e+01, -3.18617473e+02, -3.92963466e+02,
         5.57703058e+02, -2.24899017e+02, -1.32682113e+02,
         7.43180817e+01,  3.33066557e+02,  4.16433219e+02,
        -1.27556682e+01,  4.31372330e+01, -2.43000750e+02,
        -2.18885016e+02, -1.58476942e+02, -2.03354126e+02,
         2.12884302e+01, -1.96496665e+02, -3.15786975e+01,
         1.23232665e+02,  5.96689765e+01,  1.59929376e+02,
         3.08531311e-01,  3.47004052e+01, -1.78688471e+02,
         7.88662205e+01, -1.24626706e+02,  1.03581648e+02,
         1.16330471e+01,  9.68596681e+01,  1.49318445e+01,
        -1.50660211e+01, -4.42361705e+01, -2.32488942e+01,
        -1.39748383e+01, -1.13952181e+02, -4.59771324e+01,
         9.11524765e+01, -2.65346126e+00, -4.21336234e+01,
         3.59643592e+01,  1.24521941e+02,  2.55557948e+00,
         1.33850058e+02,  1.15322278e+01,  2.10111481e+01,
        -1.50908598e+02]])

In [44]:
clf_logreg.predict_proba(data[14].reshape(1,49))

array([[1.97913969e-09, 9.01924758e-01, 9.24697816e-03, 6.12026577e-02,
        1.15154151e-05, 2.18960539e-03, 1.84035656e-03, 3.34833602e-04,
        1.53574072e-02, 7.89188572e-03]])

In [45]:
data[18].reshape(1,49)

array([[  78.88755903, -355.51949546, -693.93137795,  392.9800926 ,
          97.342625  , -295.63042799,  358.30185586,   76.19322324,
         649.23525243, -644.74298939,  206.20065916,   52.798645  ,
         413.82121819, -381.8783961 ,  425.16672969, -251.71402518,
         232.70389308,  -89.36709425,  -21.95866065,  368.59895564,
         284.37365816, -138.61257523,   96.92276486,   -2.688074  ,
         253.4299582 , -186.52992006, -120.04414785,  405.66976251,
         119.80096022, -539.55289262,  118.02975019,  -48.34780786,
           8.39517279,  -75.0796769 , -365.50253341,  -76.25076912,
        -113.25137854, -158.92759711, -282.78791808,  118.92256248,
         -32.74499344, -297.46959391,  210.28424121,  242.3215544 ,
         184.21801778, -161.84051781,  -64.04021599,  357.41929206,
         187.13539738]])

In [46]:
clf_des_tree.predict_proba(data[18].reshape(1,49))

array([[0.        , 0.        , 0.        , 0.6741573 , 0.05617978,
        0.        , 0.26966292, 0.        , 0.        , 0.        ]])